name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t cicd-flask-app .  
    
    - name: Lint with pylint
      run: docker run cicd-flask-app pylint app.py
     

    
    - name: Test
      run: docker run cicd-flask-app pytest .Tests

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Deploy to server
      run: |
        docker stop cicd-flask-app-container || true
        docker rm cicd-flask-app-container || true 
        docker run -d -p 80:80 --name cicd-flask-app-container malateshgp/cicd-flask-app:latest
